version: '2'
services:
  initial:
    image: vulhub/opensmtpd:6.6.1p1
    ports:
      - "8825:25"
    networks:
      - red

  b:
    image: vulhub/opensmtpd:6.6.1p1
    ports: 
      - "8826:25"
    networks:
      - red
      - blue
  c:
    image: vulhub/opensmtpd:6.6.1p1
    ports: 
      - "8827:25"
    networks:
      - blue
      
# Is this thing on?
      
networks:
  red:
  blue:
