version: '2'
services:
  initial:
    image: vulhub/opensmtpd:6.6.1p1
    ports:
      - "8825:25"
    networks:
      - red

  b:
    image: vulhub/opensmtpd:6.6.1p1
    ports: 
      - "1027:8790"
    networks:
      - red
      - blue
  c:
    image: vulhub/opensmtpd:6.6.1p1
    ports: 
      - "8932:5764"
    networks:
      - blue
      

# Is this thing on?
      
networks:
  red:
  blue:
